---
micronaut:
  application:
    name: micronaut-test
  server:
    netty:
      worker:
        threads: 1
  executors:
    io:
      type: fixed
      nThreads: 50

---
micronaut:
  security:
    enabled: false
    endpoints:
      login:
        enabled: true
      logout:
        enabled: true
    session:
      enabled: true
      loginSuccessTargetUrl: /
      loginFailureTargetUrl: /

---
mongodb:
  uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}"

  
---
pebble:
  locale: en