---
micronaut:
  application:
    name: micronaut-test

---
micronaut:
  security:
    enabled: false
    endpoints:
      login:
        enabled: true
      logout:
        enabled: true
    session:
      enabled: true
      loginSuccessTargetUrl: /
      loginFailureTargetUrl: /

---
mongodb:
  uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}"

  
---
pebble:
  locale: en